#!/bin/bash
if uname | grep Linux > /dev/null; then
  xhost + > /dev/null 2>&1 && docker run --rm -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY -v $PWD:$PWD -w $PWD resultadosdigitais/rd-atom $@ > /dev/null 2>&1 &
else
  open -a -g XQuartz > /dev/null 2>&1
  IP=$(ifconfig en0 | grep inet | awk '$1=="inet" {print $2}')
  xhost + $IP > /dev/null 2>&1
  docker run --rm -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$IP:0 -v $PWD:$PWD -w $PWD resultadosdigitais/rd-atom $@ > /dev/null 2>&1 &
fi
